import { mainGameTableId } from "./MainUUIDIds/uuidGeral"
import {
  locationId1,
  locationId2,
  locationId3,
  locWorldId,
  locContinentId,
  locNationId,
  locRegionId,
  locCityId,
  locDistrictMerchantId,
  locDistrictCentralId,
  locDistrictLowerId,
  locDistrictDockId,
  locDistrictScholarsId,
  locDistrictOldId,
} from "./MainUUIDIds/uuidLocation"

type SeedModifierLocation = {
  id: string
  table_id: string
  parent_id?: string | null
  kind?: string
  name: string
  region?: string
  address?: string
  sub_region?: string
  is_indoor?: number
  other?: string
  country?: string
  area?: string
  dimensions?: string
  description?: string
  hex_size_m?: number | null
  width_hexes?: number | null
  height_hexes?: number | null
  center_q?: number
  center_r?: number
  orientation?: string
  rotation_deg?: number
  is_battlemap?: number
}

export const modifierTableLocations: SeedModifierLocation[] = [
  /* ---------------- WORLD · CONTINENT · NATION · REGION · CITY ---------------- */
  {
    id: locWorldId,
    table_id: mainGameTableId,
    parent_id: null,
    kind: 'world',
    name: 'Terrah',
    description: 'O mundo conhecido. Daqui se abre o mapa-múndi em hexes de 500 km.',
    hex_size_m: 500000,
    width_hexes: 120,
    height_hexes: 120,
    center_q: 0,
    center_r: 0,
    orientation: 'flat',
  },
  {
    id: locContinentId,
    table_id: mainGameTableId,
    parent_id: locWorldId,
    kind: 'continent',
    name: 'Thalassia',
    description: 'O continente central, lar do Império Valoriano.',
    hex_size_m: 200000,
    width_hexes: 60,
    height_hexes: 60,
    center_q: 3,
    center_r: -1,
  },
  {
    id: locNationId,
    table_id: mainGameTableId,
    parent_id: locContinentId,
    kind: 'nation',
    name: 'Valorian Empire',
    country: 'Valorian Empire',
    description: 'O império que domina as planícies do coração de Thalassia.',
    hex_size_m: 60000,
    width_hexes: 40,
    height_hexes: 40,
    center_q: 2,
    center_r: 2,
  },
  {
    id: locRegionId,
    table_id: mainGameTableId,
    parent_id: locNationId,
    kind: 'region',
    name: 'Valorian Heartland',
    region: 'Valorian Heartland',
    description: 'Planícies férteis e estradas antigas que ligam a capital ao interior.',
    hex_size_m: 20000,
    width_hexes: 24,
    height_hexes: 24,
    center_q: 0,
    center_r: 1,
  },
  {
    id: locCityId,
    table_id: mainGameTableId,
    parent_id: locRegionId,
    kind: 'city',
    name: 'Valorholm',
    sub_region: 'Capital',
    description: 'A capital do império, murada e densa, cortada pelo Rio Prateado.',
    hex_size_m: 1000,
    width_hexes: 18,
    height_hexes: 18,
    center_q: -1,
    center_r: 3,
  },

  /* ---------------- DISTRITOS ---------------- */
  {
    id: locDistrictMerchantId,
    table_id: mainGameTableId,
    parent_id: locCityId,
    kind: 'district',
    name: 'Merchant Quarter',
    region: 'Merchant Quarter',
    sub_region: 'Commerce Hub',
    country: 'Valorian Empire',
    area: 'Hubbub of stalls and workshops',
    hex_size_m: 60,
    width_hexes: 8,
    height_hexes: 8,
    center_q: 0,
    center_r: 2,
  },
  {
    id: locDistrictCentralId,
    table_id: mainGameTableId,
    parent_id: locCityId,
    kind: 'district',
    name: 'Central District',
    region: 'Central District',
    country: 'Valorian Empire',
    area: 'Administrative core',
    hex_size_m: 80,
    width_hexes: 10,
    height_hexes: 10,
    center_q: 2,
    center_r: 0,
  },
  {
    id: locDistrictLowerId,
    table_id: mainGameTableId,
    parent_id: locCityId,
    kind: 'district',
    name: 'Lower City',
    region: 'Lower City',
    country: 'Valorian Empire',
    area: 'Old quarters above the sewers',
    hex_size_m: 100,
    width_hexes: 12,
    height_hexes: 12,
    center_q: 0,
    center_r: -3,
  },
  {
    id: locDistrictDockId,
    table_id: mainGameTableId,
    parent_id: locCityId,
    kind: 'district',
    name: 'Dock District',
    region: 'Dock District',
    country: 'Valorian Empire',
    area: 'Harbor and warehouses',
    hex_size_m: 120,
    width_hexes: 12,
    height_hexes: 12,
    center_q: -3,
    center_r: 0,
  },
  {
    id: locDistrictScholarsId,
    table_id: mainGameTableId,
    parent_id: locCityId,
    kind: 'district',
    name: 'Scholars Quarter',
    region: 'Scholars Quarter',
    country: 'Valorian Empire',
    area: 'Academy and scriptoriums',
    hex_size_m: 60,
    width_hexes: 8,
    height_hexes: 8,
    center_q: 3,
    center_r: 2,
  },
  {
    id: locDistrictOldId,
    table_id: mainGameTableId,
    parent_id: locCityId,
    kind: 'district',
    name: 'Old District',
    region: 'Old District',
    country: 'Valorian Empire',
    area: 'Ruined pre-imperial sector',
    hex_size_m: 70,
    width_hexes: 8,
    height_hexes: 8,
    center_q: 1,
    center_r: -2,
  },

  /* ---------------- SITES (mapa tático = hex ~ metros) ---------------- */
  {
    id: locationId1,
    table_id: mainGameTableId,
    parent_id: locDistrictMerchantId,
    kind: 'site',
    name: "The Ironmongers' Alley",
    region: 'Merchant Quarter',
    sub_region: 'Craftsman Row',
    address: 'Behind the Great Forge',
    is_indoor: 0,
    other: 'Thick fog at dusk',
    country: 'Valorian Empire',
    area: 'Narrow passage',
    dimensions: '40m x 3m',
    description: 'A cramped alley lined with blacksmith stalls and old tenements. The clang of hammers echoes through the fog. Perfect for ambushes.',
    hex_size_m: 1,
    width_hexes: 46,
    height_hexes: 5,
    center_q: 1,
    center_r: 0,
    is_battlemap: 1,
  },
  {
    id: locationId2,
    table_id: mainGameTableId,
    parent_id: locDistrictCentralId,
    kind: 'site',
    name: "King's Market Square",
    region: 'Central District',
    sub_region: 'Commerce Hub',
    address: 'Main Plaza',
    is_indoor: 0,
    other: 'High civilian density',
    country: 'Valorian Empire',
    area: 'Open market',
    dimensions: '120m x 120m',
    description: 'A crowded marketplace full of merchants, guards, and noise. Ideal for social interactions and stealth.',
    hex_size_m: 2,
    width_hexes: 60,
    height_hexes: 60,
    center_q: 2,
    center_r: 1,
    is_battlemap: 1,
  },
  {
    id: locationId3,
    table_id: mainGameTableId,
    parent_id: locDistrictLowerId,
    kind: 'site',
    name: 'The Old Catacombs',
    region: 'Lower City',
    sub_region: 'Ancient Undercroft',
    address: 'Temple District entrance',
    is_indoor: 1,
    other: 'Foul air, risk of collapse',
    country: 'Valorian Empire',
    area: 'Underground tunnels',
    dimensions: 'Variable',
    description: 'Forgotten tunnels winding beneath the city, littered with old bones and the remnants of ancient rituals.',
    hex_size_m: 1,
    width_hexes: 30,
    height_hexes: 30,
    center_q: 2,
    center_r: 1,
    is_battlemap: 1,
  },
  {
    id: crypto.randomUUID(),
    table_id: mainGameTableId,
    parent_id: locDistrictOldId,
    kind: 'site',
    name: 'The Broken Tower',
    region: 'Old District',
    sub_region: 'Ruins',
    address: 'Hilltop Sector',
    is_indoor: 1,
    other: 'Unstable structure',
    country: 'Valorian Empire',
    area: 'Ruined structure',
    dimensions: '60m height',
    description: 'An ancient collapsed tower rumored to hold magical remnants.',
    hex_size_m: 2,
    width_hexes: 15,
    height_hexes: 15,
    center_q: 1,
    center_r: 1,
    is_battlemap: 1,
  },
  {
    id: crypto.randomUUID(),
    table_id: mainGameTableId,
    parent_id: locDistrictMerchantId,
    kind: 'site',
    name: 'The Royal Forge',
    region: 'Merchant Quarter',
    sub_region: 'Craftsman Row',
    address: 'Forge Street',
    is_indoor: 1,
    other: 'Extreme heat',
    country: 'Valorian Empire',
    area: 'Workshop',
    dimensions: '20m x 15m',
    description: 'A hot and noisy forge filled with weapons, tools, and molten metal.',
    hex_size_m: 1,
    width_hexes: 20,
    height_hexes: 15,
    center_q: 0,
    center_r: 1,
    is_battlemap: 1,
  },
  {
    id: crypto.randomUUID(),
    table_id: mainGameTableId,
    parent_id: locDistrictCentralId,
    kind: 'site',
    name: 'City Watch Barracks',
    region: 'Central District',
    sub_region: 'Security Zone',
    address: 'Guard Avenue',
    is_indoor: 1,
    other: 'High security',
    country: 'Valorian Empire',
    area: 'Military building',
    dimensions: '80m x 50m',
    description: 'Headquarters of the city guards, heavily patrolled and organized.',
    hex_size_m: 2,
    width_hexes: 40,
    height_hexes: 25,
    center_q: 0,
    center_r: 3,
    is_battlemap: 1,
  },
  {
    id: crypto.randomUUID(),
    table_id: mainGameTableId,
    parent_id: locDistrictLowerId,
    kind: 'site',
    name: 'The Shadowy Tankard',
    region: 'Lower City',
    sub_region: 'Dockside',
    address: 'Hidden stairway off Silver Street',
    is_indoor: 1,
    other: 'Frequented by the underworld',
    country: 'Valorian Empire',
    area: 'Tavern',
    dimensions: '25m x 20m',
    description: 'A dim, smoke-filled tavern where criminals and mercenaries gather away from prying eyes.',
    hex_size_m: 1,
    width_hexes: 25,
    height_hexes: 20,
    center_q: 1,
    center_r: 2,
    is_battlemap: 1,
  },
  {
    id: crypto.randomUUID(),
    table_id: mainGameTableId,
    parent_id: locDistrictDockId,
    kind: 'site',
    name: 'Abandoned Storehouse',
    region: 'Dock District',
    sub_region: 'Storage Zone',
    address: 'Pier 9',
    is_indoor: 1,
    other: 'Echoing acoustics',
    country: 'Valorian Empire',
    area: 'Storage building',
    dimensions: '100m x 70m',
    description: 'An empty storehouse with old crates and deep shadows — perfect for encounters.',
    hex_size_m: 2,
    width_hexes: 50,
    height_hexes: 35,
    center_q: 1,
    center_r: 1,
    is_battlemap: 1,
  },
  {
    id: crypto.randomUUID(),
    table_id: mainGameTableId,
    parent_id: locDistrictCentralId,
    kind: 'site',
    name: 'The Rooftops',
    region: 'Central District',
    sub_region: 'Upper Levels',
    address: 'Various buildings',
    is_indoor: 0,
    other: 'Fall risk, loose tiles',
    country: 'Valorian Empire',
    area: 'City rooftops',
    dimensions: 'Connected area',
    description: 'A dangerous network of rooftops ideal for chases and stealth movement.',
    hex_size_m: 4,
    width_hexes: 20,
    height_hexes: 20,
    center_q: 1,
    center_r: -1,
    is_battlemap: 0,
  },
  {
    id: crypto.randomUUID(),
    table_id: mainGameTableId,
    parent_id: locDistrictScholarsId,
    kind: 'site',
    name: 'The Arcane Library',
    region: 'Scholars Quarter',
    sub_region: 'Magic District',
    address: 'Knowledge Street',
    is_indoor: 1,
    other: 'Magical interference',
    country: 'Valorian Empire',
    area: 'Library',
    dimensions: '60m x 60m',
    description: 'A massive library containing forbidden knowledge and magical texts.',
    hex_size_m: 2,
    width_hexes: 30,
    height_hexes: 30,
    center_q: 1,
    center_r: 1,
    is_battlemap: 1,
  },
]