import * as NPCIds from "./MainUUIDIds/uuidNPC"
import { narration1, narration2, narration3, narration4, narration5, narration6, narration7, narration8, narration9 } from "./MainUUIDIds/uuidNarrations"
import { characterGalarhornId, characterLyraId, characterKaelId, characterNPCsIds } from "./MainUUIDIds/uuidCharacters"
import { locationId1, locationId3, locTempleId } from "./MainUUIDIds/uuidLocation"

const  modifierFocusId = crypto.randomUUID()
const  modifierCurseId = crypto.randomUUID()

const ELRIC = characterGalarhornId
const LYRA = characterLyraId
const KAEL = characterKaelId
const RIVEN = characterNPCsIds[0] as string
const THORNE = characterNPCsIds[1] as string
const SELENE = characterNPCsIds[2] as string
const BRUTE = characterNPCsIds[5] as string
const NYX = characterNPCsIds[6] as string

type SeedModifierNarrationActions = {
  id: string,
  narrations_id: string,
  queue: number,
  test: string,
  result: string,
  description: string,
  dice_roll: string,
  character_id: string,
  modificator: string,
  target: string | null,
  multitarget: boolean,
  location_id?: string | null,
  q?: number | null,
  r?: number | null,
  facing?: number | null,
}

export const  modifierNarrationsActions: SeedModifierNarrationActions[] = [
  {
    id: crypto.randomUUID(),
    narrations_id: narration1,
    queue: 1,
    test: '14',
    result: '12',
    description: 'Elric studied the guild parchment, memorising every detail of the missing persons report',
    dice_roll: '3d6 [ 6 , 4 , 2 ]',
    character_id: characterGalarhornId,
    modificator: '+3',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration1,
    queue: 2,
    test: '12',
    result: '10',
    description: 'The guild agent cautioned the party about a cloaked figure seen lurking near Ironmongers\' Alley',
    dice_roll: '3d6 [ 4 , 3 , 3 ]',
    character_id: characterNPCsIds[4] as string,
    modificator: '+1',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration1,
    queue: 3,
    test: '15',
    result: '16',
    description: 'Lyra Moonwhisper whispered a divination cantrip and detected faint magical residue on the parchment',
    dice_roll: '3d6 [ 6 , 5 , 5 ]',
    character_id: characterLyraId,
    modificator: '+5',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration2,
    queue: 1,
    test: '14',
    result: '13',
    description: 'Kael Shadowstep scaled the wall and retrieved the torn fabric, studying the embroidered sigil',
    location_id: locationId1,
    q: 16,
    r: 2,
    facing: 0,
    dice_roll: '3d6 [ 5 , 4 , 4 ]',
    character_id: KAEL,
    modificator: '+4',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration2,
    queue: 2,
    test: '12',
    result: '9',
    description: 'Lyra Moonwhisper wove a spiral of light, casting it down the alley to unmask every shadow',
    location_id: locationId1,
    q: 12,
    r: 2,
    facing: 0,
    dice_roll: '3d6 [ 3 , 3 , 3 ]',
    character_id: LYRA,
    modificator: '+1',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration2,
    queue: 3,
    test: '15',
    result: '16',
    description: 'Thorne Black shouldered through the shutters, blade drawn, and stalked toward the party',
    location_id: locationId1,
    q: 29,
    r: 1,
    facing: 3,
    dice_roll: '3d6 [ 6 , 5 , 5 ]',
    character_id: THORNE,
    modificator: '+5',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration2,
    queue: 4,
    test: '13',
    result: '14',
    description: 'Elric compared the sigil to marks from old wanted posters and confirmed a match with the Crimson Fang',
    location_id: locationId1,
    q: 13,
    r: 2,
    facing: 1,
    dice_roll: '3d6 [ 6 , 4 , 4 ]',
    character_id: ELRIC,
    modificator: '+3',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration2,
    queue: 5,
    test: '14',
    result: '12',
    description: 'Kael Shadowstep darted along the rooftops to high vantage, hollering a warning to the party below',
    location_id: locationId1,
    q: 18,
    r: 2,
    facing: 0,
    dice_roll: '3d6 [ 4 , 3 , 3 ]',
    character_id: KAEL,
    modificator: '+2',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration3,
    queue: 1,
    test: '14',
    result: '10',
    description: 'Elric parried Thorne\'s surprise strike and reposted with a low slash',
    location_id: locationId1,
    q: 11,
    r: 2,
    facing: 3,
    dice_roll: '3d6 [ 4 , 6 , 0 ]',
    character_id: ELRIC,
    modificator: '+2',
    target: THORNE,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration3,
    queue: 2,
    test: '13',
    result: '11',
    description: 'Thorne Black pressed the attack, driving Elric back with a series of heavy overhand blows',
    location_id: locationId1,
    q: 20,
    r: 2,
    facing: 3,
    dice_roll: '3d6 [ 5 , 3 , 3 ]',
    character_id: THORNE,
    modificator: '+1',
    target: ELRIC,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration3,
    queue: 3,
    test: '11',
    result: '9',
    description: 'Riven Kael shattered a lantern vat, dousing the street in sudden darkness',
    location_id: locationId1,
    q: 22,
    r: 2,
    facing: 0,
    dice_roll: '3d6 [ 3 , 4 , 4 ]',
    character_id: RIVEN,
    modificator: '+1',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration3,
    queue: 4,
    test: '16',
    result: '16',
    description: 'Lyra hurled a blinding flash into Riven\'s face, forcing him to shield his eyes',
    location_id: locationId1,
    q: 14,
    r: 2,
    facing: 0,
    dice_roll: '3d6 [ 6 , 5 , 5 ]',
    character_id: LYRA,
    modificator: '+5',
    target: RIVEN,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration3,
    queue: 5,
    test: '14',
    result: '12',
    description: 'Riven Kael shook off the dazzle and hurled a poisoned dagger at Lyra',
    location_id: locationId1,
    q: 21,
    r: 1,
    facing: 3,
    dice_roll: '3d6 [ 4 , 4 , 4 ]',
    character_id: RIVEN,
    modificator: '+2',
    target: LYRA,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration3,
    queue: 6,
    test: '15',
    result: '13',
    description: 'Elric closed on Thorne, chopping at his sword arm with a clean edge',
    location_id: locationId1,
    q: 9,
    r: 1,
    facing: 1,
    dice_roll: '3d6 [ 5 , 4 , 3 ]',
    character_id: ELRIC,
    modificator: '+3',
    target: THORNE,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration3,
    queue: 7,
    test: '16',
    result: '17',
    description: 'Thorne roared in battle fury, charging Elric with a wild berserk swing',
    location_id: locationId1,
    q: 17,
    r: 1,
    facing: 1,
    dice_roll: '3d6 [ 4 , 5 , 4 ]',
    character_id: THORNE,
    modificator: '-1',
    target: ELRIC,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration3,
    queue: 8,
    test: '15',
    result: '13',
    description: 'Kael Shadowstep circled the scrum and buried his dagger deep into Thorne\'s flank',
    location_id: locationId1,
    q: 18,
    r: 2,
    facing: 0,
    dice_roll: '3d6 [ 5 , 5 , 3 ]',
    character_id: KAEL,
    modificator: '+4',
    target: THORNE,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration3,
    queue: 9,
    test: '14',
    result: '16',
    description: 'Thorne Black lashed out blindly, slashing at Lyra in desperation',
    location_id: locationId1,
    q: 16,
    r: 1,
    facing: 2,
    dice_roll: '3d6 [ 4 , 3 , 4 ]',
    character_id: THORNE,
    modificator: '+1',
    target: LYRA,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration3,
    queue: 10,
    test: '12',
    result: '8',
    description: 'Riven Kael seized the wounded Thorne and dragged him north up the street',
    location_id: locationId1,
    q: 18,
    r: 1,
    facing: 0,
    dice_roll: '3d6 [ 3 , 2 , 3 ]',
    character_id: RIVEN,
    modificator: '0',
    target: THORNE,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration3,
    queue: 11,
    test: '12',
    result: '9',
    description: 'Riven Kael and Thorne Black vanished into the mist at the far end of the street',
    location_id: locationId1,
    q: 31,
    r: 1,
    facing: 0,
    dice_roll: '3d6 [ 3 , 3 , 3 ]',
    character_id: RIVEN,
    modificator: '0',
    target: THORNE,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration4,
    queue: 1,
    test: '12',
    result: '10',
    description: 'Elric took point with shield raised as the party descended the spiral stairs into darkness',
    location_id: locationId3,
    q: 6,
    r: 15,
    facing: 0,
    dice_roll: '3d6 [ 4 , 3 , 3 ]',
    character_id: ELRIC,
    modificator: '+2',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration4,
    queue: 2,
    test: '13',
    result: '11',
    description: 'Lyra followed close behind, torchlight casting long shadows against the vaulted ceiling',
    location_id: locationId3,
    q: 5,
    r: 15,
    facing: 0,
    dice_roll: '3d6 [ 4 , 4 , 4 ]',
    character_id: LYRA,
    modificator: '+1',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration4,
    queue: 3,
    test: '14',
    result: '12',
    description: 'Kael Shadowstep scouted ahead to the tunnel mouth, pressing an ear to the slick stone',
    location_id: locationId3,
    q: 8,
    r: 14,
    facing: 1,
    dice_roll: '3d6 [ 4 , 3 , 3 ]',
    character_id: KAEL,
    modificator: '+4',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration4,
    queue: 4,
    test: '10',
    result: '7',
    description: 'A pair of glowing eyes reflected torchlight from the tunnel ahead — a hulking figure blocked the passage',
    location_id: locationId3,
    q: 10,
    r: 15,
    facing: 3,
    dice_roll: '3d6 [ 3 , 2 , 2 ]',
    character_id: BRUTE,
    modificator: '-1',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration4,
    queue: 5,
    test: '13',
    result: '9',
    description: 'Borin Stonehelm drove a great fist into the wall, pulverising masonry to herd the party back',
    location_id: locationId3,
    q: 9,
    r: 15,
    facing: 3,
    dice_roll: '3d6 [ 4 , 5 , 4 ]',
    character_id: BRUTE,
    modificator: '+2',
    target: ELRIC,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration5,
    queue: 1,
    test: '14',
    result: '15',
    description: 'Kael tested the stone bridge with a careful step, the glyphs flaring with each footfall',
    location_id: locationId3,
    q: 16,
    r: 15,
    facing: 0,
    dice_roll: '3d6 [ 6 , 5 , 4 ]',
    character_id: KAEL,
    modificator: '+4',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration5,
    queue: 2,
    test: '13',
    result: '11',
    description: 'Elric advanced onto the bridge, shield forward to screen the others',
    location_id: locationId3,
    q: 12,
    r: 15,
    facing: 0,
    dice_roll: '3d6 [ 4 , 3 , 3 ]',
    character_id: ELRIC,
    modificator: '+2',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration5,
    queue: 3,
    test: '12',
    result: '10',
    description: 'Lyra stepped into the crossing, her arcane light still orbiting her palm',
    location_id: locationId3,
    q: 12,
    r: 14,
    facing: 0,
    dice_roll: '3d6 [ 3 , 4 , 3 ]',
    character_id: LYRA,
    modificator: '+1',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration5,
    queue: 4,
    test: '16',
    result: '14',
    description: 'Nyx Shadowend emerged from behind a pillar and loosed an arrow at Kael from the darkness',
    location_id: locationId3,
    q: 13,
    r: 15,
    facing: 2,
    dice_roll: '3d6 [ 5 , 5 , 4 ]',
    character_id: NYX,
    modificator: '+5',
    target: KAEL,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration5,
    queue: 5,
    test: '15',
    result: '13',
    description: 'Elric sprinted down the bridge toward Nyx\'s perch, blade drawn',
    location_id: locationId3,
    q: 9,
    r: 15,
    facing: 1,
    dice_roll: '3d6 [ 5 , 5 , 3 ]',
    character_id: ELRIC,
    modificator: '+3',
    target: NYX,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration5,
    queue: 6,
    test: '14',
    result: '12',
    description: 'Kael hurled a dagger at the archer, gouging the pillar just beside her head',
    location_id: locationId3,
    q: 17,
    r: 15,
    facing: 0,
    dice_roll: '3d6 [ 5 , 3 , 4 ]',
    character_id: KAEL,
    modificator: '+4',
    target: NYX,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration5,
    queue: 7,
    test: '12',
    result: '10',
    description: 'Lyra wove a gust of wind that snuffed the torchlight, plunging the crossing into murk',
    location_id: locationId3,
    q: 11,
    r: 14,
    facing: 2,
    dice_roll: '3d6 [ 4 , 5 , 3 ]',
    character_id: LYRA,
    modificator: '+3',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration6,
    queue: 1,
    test: '18',
    result: '17',
    description: 'Selene Voss turned from the pulsating crystal, her hands crackling with shadowy energy as she chanted the final incantation',
    location_id: locTempleId,
    q: 1,
    r: 0,
    facing: 5,
    dice_roll: '3d6 [ 6 , 6 , 5 ]',
    character_id: SELENE,
    modificator: '+5',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration6,
    queue: 2,
    test: '15',
    result: '16',
    description: 'Kael pressed a hand to his temple, the crystal\'s tremor clawing at his mind',
    location_id: locTempleId,
    q: 1,
    r: 1,
    facing: 0,
    dice_roll: '3d6 [ 5 , 4 , 3 ]',
    character_id: KAEL,
    modificator: '-1',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration6,
    queue: 3,
    test: '13',
    result: '11',
    description: 'Lyra advanced behind the party, staff raised and ready to counterspell',
    location_id: locTempleId,
    q: 2,
    r: 1,
    facing: 3,
    dice_roll: '3d6 [ 4 , 4 , 4 ]',
    character_id: LYRA,
    modificator: '+2',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration6,
    queue: 4,
    test: '14',
    result: '12',
    description: 'Elric charged across the temple floor with sword drawn, shouting to shatter the mage\'s concentration',
    location_id: locTempleId,
    q: 1,
    r: 1,
    facing: 0,
    dice_roll: '3d6 [ 5 , 4 , 3 ]',
    character_id: ELRIC,
    modificator: '+2',
    target: SELENE,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration6,
    queue: 5,
    test: '16',
    result: '18',
    description: 'Selene snarled and hurled a bolt of shadow that gouged the flagstones at Elric\'s feet',
    location_id: locTempleId,
    q: 1,
    r: 0,
    facing: 0,
    dice_roll: '3d6 [ 4 , 3 , 5 ]',
    character_id: SELENE,
    modificator: '+2',
    target: ELRIC,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration7,
    queue: 1,
    test: '15',
    result: '13',
    description: 'Lyra ran her hand along the grime-caked wall, the divination cantrip warming where a seam hid',
    location_id: locationId1,
    q: 11,
    r: 2,
    facing: 0,
    dice_roll: '3d6 [ 5 , 4 , 4 ]',
    character_id: LYRA,
    modificator: '+5',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration7,
    queue: 2,
    test: '14',
    result: '12',
    description: 'Kael prized the loose plank aside, revealing a narrow stairwell plunging into the dark',
    location_id: locationId1,
    q: 13,
    r: 2,
    facing: 0,
    dice_roll: '3d6 [ 5 , 5 , 3 ]',
    character_id: KAEL,
    modificator: '+4',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration7,
    queue: 3,
    test: '14',
    result: '13',
    description: 'Elric sheathed his sword and descended first, torch held low',
    location_id: locationId1,
    q: 14,
    r: 2,
    facing: 1,
    dice_roll: '3d6 [ 4 , 3 , 4 ]',
    character_id: ELRIC,
    modificator: '+2',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration7,
    queue: 4,
    test: '13',
    result: '11',
    description: 'Lyra followed into the stairwell, her light drawing tight around her shoulders',
    location_id: locationId1,
    q: 12,
    r: 2,
    facing: 3,
    dice_roll: '3d6 [ 3 , 4 , 4 ]',
    character_id: LYRA,
    modificator: '+1',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration7,
    queue: 5,
    test: '13',
    result: '12',
    description: 'Kael lingered at the threshold, scanning the street for watchers before pulling the plank shut',
    location_id: locationId1,
    q: 15,
    r: 2,
    facing: 3,
    dice_roll: '3d6 [ 4 , 5 , 4 ]',
    character_id: KAEL,
    modificator: '+3',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration7,
    queue: 6,
    test: '15',
    result: '14',
    description: 'Elric reached the bottom landing, finding a bolt-hole door carved with the Crimson Fang mark',
    location_id: locationId1,
    q: 18,
    r: 2,
    facing: 0,
    dice_roll: '3d6 [ 5 , 5 , 5 ]',
    character_id: ELRIC,
    modificator: '+3',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration7,
    queue: 7,
    test: '15',
    result: '13',
    description: 'Lyra and Kael joined Elric at the landing; she unsealed the lock with a whispered cantrip',
    location_id: locationId1,
    q: 19,
    r: 2,
    facing: 0,
    dice_roll: '3d6 [ 6 , 5 , 4 ]',
    character_id: LYRA,
    modificator: '+4',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration8,
    queue: 1,
    test: '14',
    result: '12',
    description: 'Elric sprinted through the winding tunnel, the roar of pursuit thundering behind',
    location_id: locationId3,
    q: 12,
    r: 15,
    facing: 3,
    dice_roll: '3d6 [ 5 , 4 , 3 ]',
    character_id: ELRIC,
    modificator: '+2',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration8,
    queue: 2,
    test: '14',
    result: '13',
    description: 'Lyra chanted as she ran, trailing frost along the flagstones',
    location_id: locationId3,
    q: 12,
    r: 14,
    facing: 3,
    dice_roll: '3d6 [ 6 , 5 , 3 ]',
    character_id: LYRA,
    modificator: '+4',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration8,
    queue: 3,
    test: '14',
    result: '12',
    description: 'Kael vaulted a collapsed column, scanning ahead for the vault door',
    location_id: locationId3,
    q: 14,
    r: 15,
    facing: 0,
    dice_roll: '3d6 [ 5 , 5 , 2 ]',
    character_id: KAEL,
    modificator: '+4',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration8,
    queue: 4,
    test: '12',
    result: '8',
    description: 'A grinding rumble filled the passage — Borin Stonehelm smashed through the rubble close behind',
    location_id: locationId3,
    q: 7,
    r: 15,
    facing: 1,
    dice_roll: '3d6 [ 3 , 3 , 3 ]',
    character_id: BRUTE,
    modificator: '0',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration8,
    queue: 5,
    test: '14',
    result: '12',
    description: 'Lyra snapped her fingers, sealing the tunnel in a sudden sheet of slippery ice',
    location_id: locationId3,
    q: 10,
    r: 15,
    facing: 2,
    dice_roll: '3d6 [ 5 , 3 , 4 ]',
    character_id: LYRA,
    modificator: '+3',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration8,
    queue: 6,
    test: '15',
    result: '13',
    description: 'Borin\'s charge stuttered on the ice; Elric hauled the vault door shut and threw the bolt',
    location_id: locationId3,
    q: 10,
    r: 15,
    facing: 0,
    dice_roll: '3d6 [ 6 , 4 , 4 ]',
    character_id: ELRIC,
    modificator: '+3',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration9,
    queue: 1,
    test: '15',
    result: '13',
    description: 'Elric drove his shoulder through the chamber entrance, the crystal blazing with trapped light',
    location_id: locTempleId,
    q: 1,
    r: 1,
    facing: 0,
    dice_roll: '3d6 [ 5 , 5 , 4 ]',
    character_id: ELRIC,
    modificator: '+3',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration9,
    queue: 2,
    test: '18',
    result: '17',
    description: 'Selene poured the last of the spell into the crystal, its light swelling to a blinding white',
    location_id: locTempleId,
    q: 1,
    r: 0,
    facing: 5,
    dice_roll: '3d6 [ 6 , 6 , 6 ]',
    character_id: SELENE,
    modificator: '+5',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration9,
    queue: 3,
    test: '14',
    result: '12',
    description: 'Lyra frantically scribed a countersigil in the air before the central altar',
    location_id: locTempleId,
    q: 2,
    r: 1,
    facing: 2,
    dice_roll: '3d6 [ 4 , 5 , 4 ]',
    character_id: LYRA,
    modificator: '+4',
    target: null,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration9,
    queue: 4,
    test: '16',
    result: '14',
    description: 'Elric swung with all his might, the blade shattering the crystal in a cascade of light',
    location_id: locTempleId,
    q: 1,
    r: 1,
    facing: 0,
    dice_roll: '3d6 [ 6 , 5 , 5 ]',
    character_id: ELRIC,
    modificator: '+2',
    target: SELENE,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration9,
    queue: 5,
    test: '14',
    result: '16',
    description: 'The shards rained down and Selene staggered, screaming as the ritual unravelled around her',
    location_id: locTempleId,
    q: 1,
    r: 0,
    facing: 0,
    dice_roll: '3d6 [ 4 , 4 , 4 ]',
    character_id: SELENE,
    modificator: '0',
    target: ELRIC,
    multitarget: false,
  },
  {
    id: crypto.randomUUID(),
    narrations_id: narration9,
    queue: 6,
    test: '13',
    result: '12',
    description: 'Silence settled in the drifting dust as the shadow over the old kingdom finally lifted',
    location_id: locTempleId,
    q: 1,
    r: 1,
    facing: 0,
    dice_roll: '3d6 [ 3 , 3 , 3 ]',
    character_id: ELRIC,
    modificator: '0',
    target: null,
    multitarget: false,
  },
]

type SeedModifierEntry = {
  id: string
  action_id: string
  character_id: string
  narration_id: string
  name: string
  description: string
  hp?: number
  st?: number
  dx?: number
  iq?: number
  ht?: number
  fatigue?: number
  mod_hp?: number
  mod_st?: number
  mod_dx?: number
  mod_iq?: number
  mod_ht?: number
  mod_fatigue?: number
  damage_value?: string
  skill_value?: string
  item_quantity?: number
  item_weight?: number
}

const actionsById = (narrations_id: string, queue: number) =>
  modifierNarrationsActions.find(
    (a) => a.narrations_id === narrations_id && a.queue === queue,
  )!.id

export const modifierSeedEntries: SeedModifierEntry[] = [
  {
    id: crypto.randomUUID(),
    action_id: actionsById(narration1, 3),
    character_id: LYRA,
    narration_id: narration1,
    name: 'Cantrip surge',
    description: 'Lyra channels residual arcane energy to recover spent fatigue',
    mod_fatigue: 1,
  },
  {
    id: crypto.randomUUID(),
    action_id: actionsById(narration2, 1),
    character_id: KAEL,
    narration_id: narration2,
    name: 'Spider\'s climb',
    description: 'Kael\'s wall climb left him short of breath',
    mod_fatigue: -1,
  },
  {
    id: crypto.randomUUID(),
    action_id: actionsById(narration3, 1),
    character_id: THORNE,
    narration_id: narration3,
    name: 'Slash wound',
    description: 'Elric landed a deep slash across Thorne\'s flank',
    mod_hp: -4,
  },
  {
    id: crypto.randomUUID(),
    action_id: actionsById(narration3, 2),
    character_id: ELRIC,
    narration_id: narration3,
    name: 'Blunt trauma',
    description: 'Thorne\'s heavy overhand blows bruised Elric through his guard',
    mod_hp: -3,
  },
  {
    id: crypto.randomUUID(),
    action_id: actionsById(narration3, 4),
    character_id: RIVEN,
    narration_id: narration3,
    name: 'Dazzled',
    description: 'Lyra\'s blinding flash left Riven disoriented',
    mod_dx: -2,
  },
  {
    id: crypto.randomUUID(),
    action_id: actionsById(narration3, 5),
    character_id: LYRA,
    narration_id: narration3,
    name: 'Dagger wound',
    description: 'Riven\'s poisoned dagger caught Lyra in the shoulder',
    mod_hp: -2,
  },
  {
    id: crypto.randomUUID(),
    action_id: actionsById(narration3, 7),
    character_id: ELRIC,
    narration_id: narration3,
    name: 'Battle fury',
    description: 'The berserk exchange drained Elric\'s stamina',
    mod_fatigue: -1,
  },
  {
    id: crypto.randomUUID(),
    action_id: actionsById(narration3, 8),
    character_id: THORNE,
    narration_id: narration3,
    name: 'Kidney stab',
    description: 'Kael\'s dagger drove deep into Thorne\'s kidney',
    mod_hp: -5,
  },
  {
    id: crypto.randomUUID(),
    action_id: actionsById(narration4, 5),
    character_id: BRUTE,
    narration_id: narration4,
    name: 'Lumbering',
    description: 'Borin\'s heavy swing left him off balance',
    mod_dx: -1,
  },
  {
    id: crypto.randomUUID(),
    action_id: actionsById(narration5, 4),
    character_id: KAEL,
    narration_id: narration5,
    name: 'Arrow wound',
    description: 'Nyx\'s arrow pierced Kael\'s shoulder',
    mod_hp: -3,
  },
  {
    id: crypto.randomUUID(),
    action_id: actionsById(narration5, 5),
    character_id: ELRIC,
    narration_id: narration5,
    name: 'Bridge sprint',
    description: 'The reckless sprint down the bridge cost Elric his breath',
    mod_fatigue: -1,
  },
  {
    id: crypto.randomUUID(),
    action_id: actionsById(narration6, 2),
    character_id: KAEL,
    narration_id: narration6,
    name: 'Channelling overload',
    description: 'The crystal\'s tremor short-circuited Kael\'s reflexes',
    mod_dx: -1,
  },
  {
    id: crypto.randomUUID(),
    action_id: actionsById(narration8, 5),
    character_id: BRUTE,
    narration_id: narration8,
    name: 'Icy footprint',
    description: 'The conjured ice robbed Borin of solid footing',
    mod_dx: -1,
  },
  {
    id: crypto.randomUUID(),
    action_id: actionsById(narration9, 2),
    character_id: SELENE,
    narration_id: narration9,
    name: 'Crystal backlash',
    description: 'The overcharged crystal scorched Selene\'s hands',
    mod_hp: -2,
  },
  {
    id: crypto.randomUUID(),
    action_id: actionsById(narration9, 5),
    character_id: SELENE,
    narration_id: narration9,
    name: 'Near-mortal wound',
    description: 'The shattering crystal ripped through Selene as she screamed',
    mod_hp: -6,
    mod_ht: -1,
  },
  {
    id: crypto.randomUUID(),
    action_id: actionsById(narration9, 4),
    character_id: SELENE,
    narration_id: narration9,
    name: 'Ritual unravelled',
    description: 'The broken ritual sapped the last of Selene\'s strength',
    mod_st: -2,
  },
]

type SeedModifierNarrationCharacter= {
  id: string
  character_id: string
  narrations_id: string
  conscious?: boolean
  q?: number | null
  r?: number | null
  facing?: number | null
}

export const  modifierNarrationsCharacters: SeedModifierNarrationCharacter[] = [
  {
    id: crypto.randomUUID(),
    character_id: characterGalarhornId,
    narrations_id: narration1,
    conscious: true,
    q: null,
    r: null,
    facing: null
  },
  {
    id: crypto.randomUUID(),
    character_id: characterLyraId,
    narrations_id: narration1,
    conscious: true,
    q: null,
    r: null,
    facing: null
  },
  {
    id: crypto.randomUUID(),
    character_id: characterKaelId,
    narrations_id: narration1,
    conscious: true,
    q: null,
    r: null,
    facing: null
  },
  {
    id: crypto.randomUUID(),
    character_id: characterGalarhornId,
    narrations_id: narration2,
    conscious: true,
    q: 13,
    r: 2,
    facing: 0
  },
  {
    id: crypto.randomUUID(),
    character_id: characterLyraId,
    narrations_id: narration2,
    conscious: true,
    q: 12,
    r: 2,
    facing: 0
  },
  {
    id: crypto.randomUUID(),
    character_id: characterKaelId,
    narrations_id: narration2,
    conscious: true,
    q: 16,
    r: 2,
    facing: 0
  },
  {
    id: crypto.randomUUID(),
    character_id: characterGalarhornId,
    narrations_id: narration3,
    conscious: true,
    q: 13,
    r: 2,
    facing: 3
  },
  {
    id: crypto.randomUUID(),
    character_id: characterLyraId,
    narrations_id: narration3,
    conscious: true,
    q: 12,
    r: 2,
    facing: 0
  },
  {
    id: crypto.randomUUID(),
    character_id: characterKaelId,
    narrations_id: narration3,
    conscious: true,
    q: 18,
    r: 2,
    facing: 0
  },
  {
    id: crypto.randomUUID(),
    character_id: characterGalarhornId,
    narrations_id: narration4,
    conscious: true,
    q: 6,
    r: 15,
    facing: 0
  },
  {
    id: crypto.randomUUID(),
    character_id: characterLyraId,
    narrations_id: narration4,
    conscious: true,
    q: 5,
    r: 15,
    facing: 0
  },
  {
    id: crypto.randomUUID(),
    character_id: characterKaelId,
    narrations_id: narration4,
    conscious: true,
    q: 8,
    r: 14,
    facing: 1
  },
  {
    id: crypto.randomUUID(),
    character_id: characterGalarhornId,
    narrations_id: narration5,
    conscious: true,
    q: 12,
    r: 15,
    facing: 0
  },
  {
    id: crypto.randomUUID(),
    character_id: characterLyraId,
    narrations_id: narration5,
    conscious: true,
    q: 12,
    r: 14,
    facing: 0
  },
  {
    id: crypto.randomUUID(),
    character_id: characterKaelId,
    narrations_id: narration5,
    conscious: true,
    q: 16,
    r: 15,
    facing: 0
  },
  {
    id: crypto.randomUUID(),
    character_id: characterGalarhornId,
    narrations_id: narration6,
    conscious: true,
    q: 1,
    r: 1,
    facing: 0
  },
  {
    id: crypto.randomUUID(),
    character_id: characterLyraId,
    narrations_id: narration6,
    conscious: true,
    q: 2,
    r: 1,
    facing: 3
  },
  {
    id: crypto.randomUUID(),
    character_id: characterKaelId,
    narrations_id: narration6,
    conscious: true,
    q: 1,
    r: 1,
    facing: 0
  },
  {
    id: crypto.randomUUID(),
    character_id: characterGalarhornId,
    narrations_id: narration7,
    conscious: true,
    q: 13,
    r: 2,
    facing: 0
  },
  {
    id: crypto.randomUUID(),
    character_id: characterLyraId,
    narrations_id: narration7,
    conscious: true,
    q: 11,
    r: 2,
    facing: 0
  },
  {
    id: crypto.randomUUID(),
    character_id: characterKaelId,
    narrations_id: narration7,
    conscious: true,
    q: 12,
    r: 2,
    facing: 0
  },
  {
    id: crypto.randomUUID(),
    character_id: characterGalarhornId,
    narrations_id: narration8,
    conscious: true,
    q: 12,
    r: 15,
    facing: 3
  },
  {
    id: crypto.randomUUID(),
    character_id: characterLyraId,
    narrations_id: narration8,
    conscious: true,
    q: 12,
    r: 14,
    facing: 3
  },
  {
    id: crypto.randomUUID(),
    character_id: characterKaelId,
    narrations_id: narration8,
    conscious: true,
    q: 14,
    r: 15,
    facing: 0
  },
  {
    id: crypto.randomUUID(),
    character_id: characterGalarhornId,
    narrations_id: narration9,
    conscious: true,
    q: 1,
    r: 1,
    facing: 0
  },
  {
    id: crypto.randomUUID(),
    character_id: characterLyraId,
    narrations_id: narration9,
    conscious: true,
    q: 2,
    r: 1,
    facing: 2
  },
  {
    id: crypto.randomUUID(),
    character_id: characterKaelId,
    narrations_id: narration9,
    conscious: true,
    q: 1,
    r: 2,
    facing: 3
  },
]

type SeedModifierNarrationNPCs= {
  id: string,
  narration_id: string,
  npc_id: string,
  q?: number | null,
  r?: number | null,
  facing?: number | null,
}

export const  modifierNarrationsNPCs: SeedModifierNarrationNPCs[] = [
  {
    id: crypto.randomUUID(),
    narration_id: narration1,
    npc_id: NPCIds.Npc5Id,
    q: null,
    r: null,
    facing: null
  },
  {
    id: crypto.randomUUID(),
    narration_id: narration2,
    npc_id: NPCIds.Npc2Id,
    q: 30,
    r: 1,
    facing: 3
  },
  {
    id: crypto.randomUUID(),
    narration_id: narration3,
    npc_id: NPCIds.Npc1Id,
    q: 23,
    r: 1,
    facing: 0
  },
  {
    id: crypto.randomUUID(),
    narration_id: narration3,
    npc_id: NPCIds.Npc2Id,
    q: 25,
    r: 1,
    facing: 3
  },
  {
    id: crypto.randomUUID(),
    narration_id: narration4,
    npc_id: NPCIds.Npc6Id,
    q: 10,
    r: 15,
    facing: 3
  },
  {
    id: crypto.randomUUID(),
    narration_id: narration5,
    npc_id: NPCIds.Npc7Id,
    q: 13,
    r: 15,
    facing: 2
  },
  {
    id: crypto.randomUUID(),
    narration_id: narration6,
    npc_id: NPCIds.Npc3Id,
    q: 1,
    r: 0,
    facing: 5
  },
  {
    id: crypto.randomUUID(),
    narration_id: narration8,
    npc_id: NPCIds.Npc6Id,
    q: 7,
    r: 15,
    facing: 1
  },
  {
    id: crypto.randomUUID(),
    narration_id: narration9,
    npc_id: NPCIds.Npc3Id,
    q: 1,
    r: 0,
    facing: 5
  },
]

type SeedModifierNarrationLocations= {
  id: string,
  location_id: string,
  narrations_id: string,
}

export const  modifierNarrationsLocations: SeedModifierNarrationLocations[] = [
  {
    id: crypto.randomUUID(),
    location_id: locationId1,
    narrations_id: narration2
  },
  {
    id: crypto.randomUUID(),
    location_id: locationId1,
    narrations_id: narration3
  },
  {
    id: crypto.randomUUID(),
    location_id: locationId3,
    narrations_id: narration4
  },
  {
    id: crypto.randomUUID(),
    location_id: locationId3,
    narrations_id: narration5
  },
  {
    id: crypto.randomUUID(),
    location_id: locTempleId,
    narrations_id: narration6
  },
  {
    id: crypto.randomUUID(),
    location_id: locationId1,
    narrations_id: narration7
  },
  {
    id: crypto.randomUUID(),
    location_id: locationId3,
    narrations_id: narration8
  },
  {
    id: crypto.randomUUID(),
    location_id: locTempleId,
    narrations_id: narration9
  },
]