import crypto from 'crypto'

export const  shortSwordId = crypto.randomUUID()
export const  daggerId = crypto.randomUUID()
export const  leatherArmorId = crypto.randomUUID()
export const  bowId = crypto.randomUUID()
export const  wizardStaffId = crypto.randomUUID()
export const  spellbookId = crypto.randomUUID()
export const  robesId = crypto.randomUUID()
export const  potionBeltId = crypto.randomUUID()
export const  fineDaggerId = crypto.randomUUID()
export const  throwingKnifeId = crypto.randomUUID()
export const  lockpickSetId = crypto.randomUUID()
export const  darkHoodedCloakId = crypto.randomUUID()
export const  galhornLeatherArmorId = crypto.randomUUID()
export const  leatherBracersId = crypto.randomUUID()
export const  leatherBootsId = crypto.randomUUID()
export const  mediumShieldId = crypto.randomUUID()
export const  travelCloakId = crypto.randomUUID()
export const  kaelLeatherArmorId = crypto.randomUUID()