import crypto from 'crypto'

/* ---- items (game_table_items) ---- */
export const shortSwordId = crypto.randomUUID()
export const daggerId = crypto.randomUUID()
export const handAxeId = crypto.randomUUID()
export const mediumShieldId = crypto.randomUUID()
export const pistolId = crypto.randomUUID()
export const recurveBowId = crypto.randomUUID()
export const leatherArmorId = crypto.randomUUID()
export const wizardStaffId = crypto.randomUUID()
export const spellbookId = crypto.randomUUID()
export const robesId = crypto.randomUUID()
export const potionBeltId = crypto.randomUUID()
export const fineDaggerId = crypto.randomUUID()
export const throwingKnifeId = crypto.randomUUID()
export const lockpickSetId = crypto.randomUUID()
export const darkHoodedCloakId = crypto.randomUUID()
export const galhornLeatherArmorId = crypto.randomUUID()
export const leatherBracersId = crypto.randomUUID()
export const leatherBootsId = crypto.randomUUID()
export const travelCloakId = crypto.randomUUID()
export const kaelLeatherArmorId = crypto.randomUUID()

/* ---- weapons (game_table_weapons) ---- */
export const shortSwordWeaponId = crypto.randomUUID()
export const daggerWeaponId = crypto.randomUUID()
export const handAxeWeaponId = crypto.randomUUID()
export const mediumShieldWeaponId = crypto.randomUUID()
export const pistolWeaponId = crypto.randomUUID()
export const recurveBowWeaponId = crypto.randomUUID()
export const wizardStaffWeaponId = crypto.randomUUID()

/* ---- attacks (weapon_attacks) ---- */
export const shortSwordSwingId = crypto.randomUUID()
export const shortSwordThrustId = crypto.randomUUID()
export const daggerSwingId = crypto.randomUUID()
export const daggerThrustId = crypto.randomUUID()
export const handAxeSwingId = crypto.randomUUID()
export const handAxeThrustId = crypto.randomUUID()
export const mediumShieldBashId = crypto.randomUUID()
export const pistolShotId = crypto.randomUUID()
export const recurveBowShotId = crypto.randomUUID()
export const wizardStaffSwingId = crypto.randomUUID()
export const wizardStaffThrustId = crypto.randomUUID()

/* ---- armors (game_table_armors) ---- */
export const leatherArmorDefId = crypto.randomUUID()
export const robesDefId = crypto.randomUUID()
export const mediumShieldDefId = crypto.randomUUID()
export const galhornLeatherArmorDefId = crypto.randomUUID()
export const leatherBracersDefId = crypto.randomUUID()
export const leatherBootsDefId = crypto.randomUUID()
export const kaelLeatherArmorDefId = crypto.randomUUID()
