import { mainGameTableId } from "./MainUUIDIds/uuidGeral"
import {
  locationId1,
  locationId2,
  locationId3,
  locWorldId,
  locContinentId,
  locNationId,
  locRegionId,
  locCityId,
  locDistrictMerchantId,
  locDistrictCentralId,
  locDistrictLowerId,
  locDistrictDockId,
  locDistrictScholarsId,
  locDistrictOldId,
  locTempleId,
  locWatchBarracksId,
  locShadowyTankardId,
  locRooftopsId,
  locArcaneLibraryId,
} from "./MainUUIDIds/uuidLocation"

type SeedModifierLocation = {
  id: string
  table_id: string
  parent_id?: string | null
  kind?: string
  name: string
  region?: string
  address?: string
  sub_region?: string
  is_indoor?: number
  other?: string
  country?: string
  area?: string
  dimensions?: string
  description?: string
  hex_size_m?: number | null
  width_hexes?: number | null
  height_hexes?: number | null
  center_q?: number
  center_r?: number
  orientation?: string
  rotation_deg?: number
  is_battlemap?: number
  tiles?: Array<{ q: number; r: number; t: string }>
  drawing?: Array<Record<string, unknown>>
}

export const modifierTableLocations: SeedModifierLocation[] = [
  /* ---------------- WORLD · CONTINENT · NATION · REGION · CITY ---------------- */
  {
    id: locWorldId,
    table_id: mainGameTableId,
    parent_id: null,
    kind: 'world',
    name: 'Terrah',
    description: 'O mundo conhecido. Daqui se abre o mapa-múndi em hexes de 500 km.',
    hex_size_m: 500000,
    width_hexes: 120,
    height_hexes: 120,
    center_q: 0,
    center_r: 0,
    orientation: 'flat',
  },
  {
    id: locContinentId,
    table_id: mainGameTableId,
    parent_id: locWorldId,
    kind: 'continent',
    name: 'Thalassia',
    description: 'O continente central, lar do Império Valoriano.',
    hex_size_m: 200000,
    width_hexes: 60,
    height_hexes: 60,
    center_q: 3,
    center_r: -1,
  },
  {
    id: locNationId,
    table_id: mainGameTableId,
    parent_id: locContinentId,
    kind: 'nation',
    name: 'Valorian Empire',
    country: 'Valorian Empire',
    description: 'O império que domina as planícies do coração de Thalassia.',
    hex_size_m: 60000,
    width_hexes: 40,
    height_hexes: 40,
    center_q: 2,
    center_r: 2,
  },
  {
    id: locRegionId,
    table_id: mainGameTableId,
    parent_id: locNationId,
    kind: 'region',
    name: 'Valorian Heartland',
    region: 'Valorian Heartland',
    description: 'Planícies férteis e estradas antigas que ligam a capital ao interior.',
    hex_size_m: 20000,
    width_hexes: 24,
    height_hexes: 24,
    center_q: 0,
    center_r: 1,
  },
  {
    id: locCityId,
    table_id: mainGameTableId,
    parent_id: locRegionId,
    kind: 'city',
    name: 'Valorholm',
    sub_region: 'Capital',
    description: 'A capital do império, murada e densa, cortada pelo Rio Prateado.',
    hex_size_m: 1000,
    width_hexes: 18,
    height_hexes: 18,
    center_q: -1,
    center_r: 3,
  },

  /* ---------------- DISTRITOS ---------------- */
  {
    id: locDistrictMerchantId,
    table_id: mainGameTableId,
    parent_id: locCityId,
    kind: 'district',
    name: 'Distrito dos Mercadores',
    region: 'Distrito dos Mercadores',
    sub_region: 'Polo Comercial',
    country: 'Valorian Empire',
    area: 'Agito de barracas e oficinas',
    hex_size_m: 60,
    width_hexes: 8,
    height_hexes: 8,
    center_q: 0,
    center_r: 2,
  },
  {
    id: locDistrictCentralId,
    table_id: mainGameTableId,
    parent_id: locCityId,
    kind: 'district',
    name: 'Distrito Central',
    region: 'Distrito Central',
    country: 'Valorian Empire',
    area: 'Núcleo administrativo',
    hex_size_m: 80,
    width_hexes: 10,
    height_hexes: 10,
    center_q: 2,
    center_r: 0,
  },
  {
    id: locDistrictLowerId,
    table_id: mainGameTableId,
    parent_id: locCityId,
    kind: 'district',
    name: 'Cidade Baixa',
    region: 'Cidade Baixa',
    country: 'Valorian Empire',
    area: 'Bairros antigos acima dos esgotos',
    hex_size_m: 100,
    width_hexes: 12,
    height_hexes: 12,
    center_q: 0,
    center_r: -3,
  },
  {
    id: locDistrictDockId,
    table_id: mainGameTableId,
    parent_id: locCityId,
    kind: 'district',
    name: 'Distrito Portuário',
    region: 'Distrito Portuário',
    country: 'Valorian Empire',
    area: 'Porto e armazéns',
    hex_size_m: 120,
    width_hexes: 12,
    height_hexes: 12,
    center_q: -3,
    center_r: 0,
  },
  {
    id: locDistrictScholarsId,
    table_id: mainGameTableId,
    parent_id: locCityId,
    kind: 'district',
    name: 'Distrito dos Estudiosos',
    region: 'Distrito dos Estudiosos',
    country: 'Valorian Empire',
    area: 'Academia e scriptórios',
    hex_size_m: 60,
    width_hexes: 8,
    height_hexes: 8,
    center_q: 3,
    center_r: 2,
  },
  {
    id: locDistrictOldId,
    table_id: mainGameTableId,
    parent_id: locCityId,
    kind: 'district',
    name: 'Distrito Antigo',
    region: 'Distrito Antigo',
    country: 'Valorian Empire',
    area: 'Setor pré-imperial em ruínas',
    hex_size_m: 70,
    width_hexes: 8,
    height_hexes: 8,
    center_q: 1,
    center_r: -2,
  },

  /* ---------------- SITES (mapa tático = hex ~ metros) ---------------- */
  {
    id: locationId1,
    table_id: mainGameTableId,
    parent_id: locDistrictMerchantId,
    kind: 'site',
    name: 'Beco dos Ferreiros',
    region: 'Distrito dos Mercadores',
    sub_region: 'Rua dos Artesãos',
    address: 'Atrás da Grande Forja',
    is_indoor: 0,
    other: 'Névoa densa ao anoitecer',
    country: 'Valorian Empire',
    area: 'Passagem estreita',
    dimensions: '40m x 3m',
    description: 'Um beco apertado, ladeado por barracas de ferreiros e velhas habitações. O estampido dos martelos ecoa pela névoa. Perfeito para emboscadas.',
    hex_size_m: 1,
    width_hexes: 46,
    height_hexes: 5,
    center_q: 1,
    center_r: 0,
    is_battlemap: 1,
  },
  {
    id: locationId2,
    table_id: mainGameTableId,
    parent_id: locDistrictCentralId,
    kind: 'site',
    name: 'Praça do Mercado do Rei',
    region: 'Distrito Central',
    sub_region: 'Polo Comercial',
    address: 'Praça Principal',
    is_indoor: 0,
    other: 'Alta densidade civil',
    country: 'Valorian Empire',
    area: 'Mercado a céu aberto',
    dimensions: '120m x 120m',
    description: 'Um mercado superlotado, cheio de mercadores, guardas e barulho. Ideal para interações sociais e furtividade.',
    hex_size_m: 2,
    width_hexes: 60,
    height_hexes: 60,
    center_q: 2,
    center_r: 1,
    is_battlemap: 1,
  },
  {
    id: locationId3,
    table_id: mainGameTableId,
    parent_id: locDistrictLowerId,
    kind: 'site',
    name: 'As Catacumbas Antigas',
    region: 'Cidade Baixa',
    sub_region: 'Cripta Antiga',
    address: 'Entrada do Distrito do Templo',
    is_indoor: 1,
    other: 'Ar viciado, risco de desabamento',
    country: 'Valorian Empire',
    area: 'Túneis subterrâneos',
    dimensions: 'Variável',
    description: 'Túneis esquecidos que serpenteiam sob a cidade, cobertos de ossos antigos e restos de rituais ancestrais.',
    hex_size_m: 1,
    width_hexes: 30,
    height_hexes: 30,
    center_q: 2,
    center_r: 1,
    is_battlemap: 1,
  },
  {
    id: crypto.randomUUID(),
    table_id: mainGameTableId,
    parent_id: locDistrictOldId,
    kind: 'site',
    name: 'A Torre Quebrada',
    region: 'Distrito Antigo',
    sub_region: 'Ruínas',
    address: 'Setor do Topo da Colina',
    is_indoor: 1,
    other: 'Estrutura instável',
    country: 'Valorian Empire',
    area: 'Estrutura em ruínas',
    dimensions: '60m de altura',
    description: 'Uma torre antiga em colapso que, segundo rumores, abriga remanescentes mágicos.',
    hex_size_m: 2,
    width_hexes: 15,
    height_hexes: 15,
    center_q: 1,
    center_r: 1,
    is_battlemap: 1,
  },
  {
    id: crypto.randomUUID(),
    table_id: mainGameTableId,
    parent_id: locDistrictMerchantId,
    kind: 'site',
    name: 'A Forja Real',
    region: 'Distrito dos Mercadores',
    sub_region: 'Rua dos Artesãos',
    address: 'Rua da Forja',
    is_indoor: 1,
    other: 'Calor extremo',
    country: 'Valorian Empire',
    area: 'Oficina',
    dimensions: '20m x 15m',
    description: 'Uma forja quente e barulhenta, cheia de armas, ferramentas e metal derretido.',
    hex_size_m: 1,
    width_hexes: 20,
    height_hexes: 15,
    center_q: 0,
    center_r: 1,
    is_battlemap: 1,
  },
  {
    id: locWatchBarracksId,
    table_id: mainGameTableId,
    parent_id: locDistrictCentralId,
    kind: 'site',
    name: 'Quartel da Guarda da Cidade',
    region: 'Distrito Central',
    sub_region: 'Zona de Segurança',
    address: 'Avenida da Guarda',
    is_indoor: 1,
    other: 'Alta segurança',
    country: 'Valorian Empire',
    area: 'Edifício militar',
    dimensions: '80m x 50m',
    description: 'Quartel-general da guarda da cidade, fortemente patrulhado e organizado.',
    hex_size_m: 2,
    width_hexes: 40,
    height_hexes: 25,
    center_q: 0,
    center_r: 3,
    is_battlemap: 1,
  },
  {
    id: locShadowyTankardId,
    table_id: mainGameTableId,
    parent_id: locDistrictLowerId,
    kind: 'site',
    name: 'O Caneco Sombrio',
    region: 'Cidade Baixa',
    sub_region: 'Orla do Porto',
    address: 'Escadaria secreta na Rua Prateada',
    is_indoor: 1,
    other: 'Frequentado pelo submundo',
    country: 'Valorian Empire',
    area: 'Taverna',
    dimensions: '25m x 20m',
    description: 'Uma taverna sombria e cheia de fumaça, onde criminosos e mercenários se reúnem longe de olhares curiosos.',
    hex_size_m: 1,
    width_hexes: 25,
    height_hexes: 20,
    center_q: 1,
    center_r: 2,
    is_battlemap: 1,
  },
  {
    id: crypto.randomUUID(),
    table_id: mainGameTableId,
    parent_id: locDistrictDockId,
    kind: 'site',
    name: 'Armazém Abandonado',
    region: 'Distrito Portuário',
    sub_region: 'Zona de Armazenagem',
    address: 'Cais 9',
    is_indoor: 1,
    other: 'Acústica ecoante',
    country: 'Valorian Empire',
    area: 'Edifício de armazenagem',
    dimensions: '100m x 70m',
    description: 'Um armazém vazio com velhas caixas e sombras profundas — perfeito para encontros.',
    hex_size_m: 2,
    width_hexes: 50,
    height_hexes: 35,
    center_q: 1,
    center_r: 1,
    is_battlemap: 1,
  },
  {
    id: locRooftopsId,
    table_id: mainGameTableId,
    parent_id: locDistrictCentralId,
    kind: 'site',
    name: 'Os Telhados',
    region: 'Distrito Central',
    sub_region: 'Níveis Superiores',
    address: 'Diversos edifícios',
    is_indoor: 0,
    other: 'Risco de queda, telhas soltas',
    country: 'Valorian Empire',
    area: 'Telhados da cidade',
    dimensions: 'Área conectada',
    description: 'Uma rede perigosa de telhados, ideal para perseguições e movimentos furtivos.',
    hex_size_m: 4,
    width_hexes: 20,
    height_hexes: 20,
    center_q: 1,
    center_r: -1,
    is_battlemap: 0,
  },
  {
    id: locArcaneLibraryId,
    table_id: mainGameTableId,
    parent_id: locDistrictScholarsId,
    kind: 'site',
    name: 'A Biblioteca Arcana',
    region: 'Distrito dos Estudiosos',
    sub_region: 'Distrito Mágico',
    address: 'Rua do Conhecimento',
    is_indoor: 1,
    other: 'Interferência mágica',
    country: 'Valorian Empire',
    area: 'Biblioteca',
    dimensions: '60m x 60m',
    description: 'Uma biblioteca colossal que contém conhecimento proibido e textos mágicos.',
    hex_size_m: 2,
    width_hexes: 30,
    height_hexes: 30,
    center_q: 1,
    center_r: 1,
    is_battlemap: 1,
  },

  /* ---------------- THE FORGOTTEN TEMPLE — 3×3 vector battlemap ---------------- */
  {
    id: locTempleId,
    table_id: mainGameTableId,
    parent_id: locDistrictLowerId,
    kind: 'site',
    name: 'O Templo Esquecido',
    region: 'Cidade Baixa',
    sub_region: 'Cripta Antiga',
    address: 'Atrás das catacumbas',
    is_indoor: 1,
    other: 'Cristal pulsante acima do altar',
    country: 'Valorian Empire',
    area: 'Templo subterrâneo',
    dimensions: '6 m × 5.2 m',
    description:
      'Um vasto templo subterrâneo, cuja arquitetura é antiga e alienígena. Pilares de pedra erguem-se do chão e um cristal pulsante paira sobre o altar central — a fonte dos desaparecimentos.',
    hex_size_m: 2,
    width_hexes: 3,
    height_hexes: 3,
    center_q: 1,
    center_r: 1,
    orientation: 'flat',
    rotation_deg: 0,
    is_battlemap: 1,
    tiles: [
      { q: 0, r: 0, t: 'stone' },
      { q: 1, r: 0, t: 'stone' },
      { q: 2, r: 0, t: 'stone' },
      { q: 0, r: 1, t: 'door' },
      { q: 1, r: 1, t: 'stone' },
      { q: 2, r: 1, t: 'stone' },
      { q: 0, r: 2, t: 'stone' },
      { q: 1, r: 2, t: 'stone' },
      { q: 2, r: 2, t: 'stone' },
    ],
    drawing: [
      /* altar rectangle (normalised hexR units) */
      { type: 'rect', x: 0.5, y: 1.2, w: 2.0, h: 1.06, size: 0.12, color: '#e4e4e7', unit: 'hexR' },
      /* crystal glow (purple circle above altar) */
      { type: 'ellipse', cx: 1.5, cy: 1.732, rx: 0.55, ry: 0.55, size: 0.12, color: '#a78bfa', unit: 'hexR' },
      /* pillar northwest */
      { type: 'path', d: 'M -0.5 -0.45 L -0.5 0.55', size: 0.28, color: '#71767e', unit: 'hexR' },
      /* pillar southeast */
      { type: 'path', d: 'M 3.5 2.9 L 3.5 3.95', size: 0.28, color: '#71767e', unit: 'hexR' },
      /* processional path door → altar */
      { type: 'path', d: 'M 0 1.732 L 1.5 1.732', size: 0.35, color: '#9a7d2f', unit: 'hexR' },
    ],
  },
]